global:
  resolve_timeout: 5m
  smtp_smarthost: '192.168.1.112:2525'
  smtp_from: 'alertmanager@Blitzcode.com'
  smtp_require_tls: false

route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'mail-notifications'
  routes:
    - match:
        severity: 'critical'
      receiver: 'mail-notifications'
    - match:
        severity: 'warning'
      receiver: 'mail-notifications'

receivers:
  - name: 'mail-notifications'
    email_configs:
      - to: 'admin@Blitzcode.com'
        send_resolved: true
        require_tls: false
