global:
  resolve_timeout: 5m

route:
  receiver: 'grafana'

receivers:
  - name: 'grafana'
    webhook_configs:
      - url: 'http://grafana:3000/api/alerts'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'admin'
            password: 'Blitzcode1.'


