global:
  smtp_smarthost: '192.168.1.112:2525'
  smtp_from: 'alertmanager@Blitzcode.com'

route:
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'admin@Blitzcode.com'
        send_resolved: true
