groups:
  - name: alerta_de_disponibilidad
    rules:
      - alert: InstanciaCaida
        expr: up == 0
        for: 1m
        labels:
          severity: 'critical'
        annotations:
          summary: "Instancia {{ $labels.instance }} caída"
          description: "La instancia {{ $labels.instance }} del trabajo {{ $labels.job }} ha estado caída por más de 1 minuto."

  - name: alerta_de_cpu
    rules:
      - alert: UsoAltoCPU
        expr: (sum by(instance) (irate(windows_cpu_time_total{mode!="idle"}[5m])) / sum by(instance) (irate(windows_cpu_time_total[5m]))) * 100 > 90
        for: 1m
        labels:
          severity: 'critical'
        annotations:
          summary: "Uso alto de la CPU en {{ $labels.instance }}"
          description: "El uso de la CPU en la instancia {{ $labels.instance }} ha superado el umbral del 90% durante más de 1 minuto."

